### PR TITLE
Support base 4.18

### PR DESCRIPTION
**Pull request by chris-martin**
Hi, I'm back again. I've tested that this builds with base 4.18 (GHC 9.6).

### CODE REVIEW

**Comment by fumieval** [comment]
Thanks

**Comment by chris-martin** [comment]
Update on Hackage please?

**Comment by chris-martin** [comment]
(I'm willing to help maintain if you'd like.)

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision: https://hackage.haskell.org/package/data-functor-logistic-0.0/revisions/

**Pull request merged**
